repos:
  - repo: https://github.com/mercadolibre/fury_websec-git-hooks
    rev: v1.0.5
    hooks:
      - id: pre_commit_hook
        stages: [commit]
      - id: post_commit_hook
        stages: [post-commit]

# PRE_COMMIT_ALLOW_NO_CONFIG=1 git commit -m "git message"